### PR TITLE
Apply Made Tech frontend to productionisation.io

### PR DESCRIPTION
**Pull request by craigjbass**

### CODE REVIEW

**Comment by davidwinter** [comment]
I _think_ @lukemorton has a package that will wrap up all of this stuff, which is near readiness. I might be wrong though.

**Comment by craigjbass** [comment]
I copied what luke to for learn.madetech.com

**Comment by zuren** [comment]
Screenshots? 😄

**Comment by lukemorton** [comment]
Craig has followed the static asset route, which is the most appropriate for GitHub Pages unless you want to commit node_modules or Ruby Gems to the repo.

**Comment by davidwinter** [comment]
What was the thing you were working on @lukemorton that you mentioned to me?

**Pull request closed without merging**
